import type { Metadata } from "next";
import { Grand_Hotel, Rozha_One, Poppins } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";


const grandHotel = Grand_Hotel({ weight: "400", subsets: ["latin"] ,  variable: "--font-grand-hotel" });
const rozhaOne = Rozha_One({ weight: "400", subsets: ["latin"] , variable: "--font-rozha-one" });
const poppins = Poppins({ weight: ["300", "400", "500", "700"], subsets: ["latin"] ,variable: "--font-poppins" });

export const metadata: Metadata = {
  title: "Illuminate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
    className={`${grandHotel.variable} ${rozhaOne.variable} ${poppins.variable} antialiased`}
      >
         <AntdRegistry>

        {children}
         </AntdRegistry>
      </body>
    </html>
  );
}
